### ISSUE TITLE
TLS v1.1

### ISSUE THREAD

**Issue by jakubpycha** [l-ra/openeet-java#12]
Playground už nepodporuje TLS 1.1, produkce ano. TLS 1.1 je výchozí protokol v builderu, proto ve výchozím stavu knihovna nefunguje proti PG.

**Comment by jakubpycha** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=pg.eet.cz&s=5.145.105.129

**Comment by l-ra** [comment]
Diky.
