### ISSUE TITLE
Using openeet-java for Android?

### ISSUE THREAD

**Issue by kienkites** [l-ra/openeet-java#16]
Can Ị using openeet-java for Android? I am sorry but I cant find how to add/import certificate?

**Comment by l-ra** [comment]
See the README in this repository there you can find example including certificate import. 
This line reads certificate from a stream.  
```
...
.pkcs12(loadStream(getClass().getResourceAsStream("/EET_CA1_Playground-CZ1212121218.p12")))
...
```
If you want to load certificate from a file:
```
.pkcs12(loadStream(new FileInputStream("filename.p12")))
```

**Comment by mpavelka** [comment]
@kienkites I can confirm you _can_ use it with Android. We did it like this:

```
git submodule add https://github.com/l-ra/openeet-java.git
```

Add the module into your project by adding this line int `settings.gradle`:

```
project(':openeet-lite').projectDir = new File('openeet-java/openeet-lite')
```

And then add the project as a dependency in the `build.gradle` file:

```
dependencies {
    implementation project(path: ':openeet-lite')
```

Then you can access the classes such as `EetRegisterRequest.builder()`

**Comment by l-ra** [comment]
I hope all is clear. Closing this
