### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by hadmir** [l-ra/openeet-java#8]
On old telephones (TC55, Android 4.4.3, API 19), it goes: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 

Now, that new root SSL certificate is switched for EET.

Newer phones seems OK.

**Comment by l-ra** [comment]
Did you use the jar bundle or source based build? the new certificate is supported by master branch. The prebuilt jars don't include the updated trust store. It should be enough to take `eet-trust.jks` and replace it in your build.

**Comment by hadmir** [comment]
I updated .jks file, source based build.

**Comment by hadmir** [comment]
As noted, other phones are ok, only Zebra TC55, Android 4.4.3 is doing this.

**Comment by hadmir** [comment]
I am trying it on Emulator for 4.4.3 (API 19, no google services)...
So, in Android Studio emulator this Android verision (and perhaps older) is also same error. Now I will check Android 5.

**Comment by l-ra** [comment]
Do you have full stack trace available?

**Comment by hadmir** [comment]
Thanks for response, I am not at the computer now, I will try to check ASAP.

**Comment by hadmir** [comment]
Android 5 is OK, so problem is limited to KitKat 4.4.3 API 19 (perhaps earlier versions). Next: I will get full stacktrace.

**Comment by hadmir** [comment]
New information: root certificate file registered manually to Android device makes OpenEET work on 4.4.3.

**Comment by l-ra** [comment]
Thanks for research. I'm closing the issue.
